version: '3.8'

services:
  app:
    build: .
    container_name: dpp-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/attestry_dpp
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - CORS_ALLOWED_ORIGINS=https://attestry-dpp-v1-frontend.vercel.app
      - MINIO_URL=http://minio:9000
      - MINIO_PUBLIC_URL=http://storage.attestry-dpp.shop
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    depends_on:
      - postgres
      - minio
    restart: always

  postgres:
    image: postgres:15-alpine
    container_name: dpp-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: attestry_dpp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  minio:
    image: minio/minio:latest
    container_name: dpp-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_API_CORS_ALLOW_ORIGIN: "*"
      MINIO_SERVER_URL: http://storage.attestry-dpp.shop
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: always

volumes:
  postgres_data:
  minio_data:
